classification_loss:
    _target_: torch.nn.CrossEntropyLoss

# additional losses are optional and are used to regularize the model
# they can be used for moes or residual models
# for more info see peekvit/losses.py
additional_losses:
    # UniModal Approach
    # distr_prior_loss:
    #    _target_:  AdaViT.utils.losses.AViTDPriorLoss
    #   target_depth: 7
    #   weight: 0.1
    #   scaling: 1
    
    # MultiModal Approach
    distr_prior_loss:
        _target_:  AdaViT.utils.losses.AViTDPriorLoss
        target_depth: [2,10]
        weight: 0.1
        scaling: [1,1]
        weights: [0.7,0.3]
    ponder_loss:
        _target_:  AdaViT.utils.losses.AViTPonderLoss
        weight: 0.0005
