_target_: AdaViT.data.imagenette.Imagenette
root: '${workspace}/imagenette_dataset'
image_size: 160                 # used by default by model as well 
num_classes: 10                 # used by default by model as well  
augmentation_ops: 2
augmentation_magnitude: 9   