wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711782857.0
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.9.16
      5: 0.16.5
      8:
      - 2
      - 5
      13: linux-x86_64
