wandb_version: 1

logger:
  desc: null
  value:
    _target_: AdaViT.utils.logging.WandbLogger
    wandb_entity: alessioborgi3
    wandb_project: adavit
    wandb_run: 2024-04-26-11-31-30
dataset:
  desc: null
  value:
    _target_: AdaViT.data.imagenette.Imagenette
    root: AdaViT/imagenette_dataset
    image_size: 224
    num_classes: 10
    augmentation_ops: 2
    augmentation_magnitude: 9
model:
  desc: null
  value:
    _target_: AdaViT.models.adavit.AdaptiveVisionTransformer
    image_size: 224
    patch_size: 16
    num_layers: 12
    hidden_dim: 192
    mlp_dim: 768
    num_heads: 3
    eps: 0.25
    num_classes: 10
    timm_pretrained_weights:
    - facebookresearch/deit:main
    - deit_tiny_patch16_224
training:
  desc: null
  value:
    train_batch_size: 128
    eval_batch_size: 128
    clip_grad_norm: 1.0
    num_epochs: 150
    eval_every: 100
    checkpoint_every: 10
    plot_masks_every: 10
    num_images_to_plot: 10
    reinit_class_tokens: true
    train_backbone: false
    num_workers: 4
    val_budgets:
    - 0.2
    - 0.8
    train_budget: 0.9
optimizer:
  desc: null
  value:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0
loss:
  desc: null
  value:
    classification_loss:
      _target_: torch.nn.CrossEntropyLoss
    additional_losses:
      distr_prior_loss:
        _target_: AdaViT.utils.losses.AViTDPriorLoss
        target_depth:
        - 5
        - 10
        weight: 0.1
        scaling:
        - 1
        - 1
      ponder_loss:
        _target_: AdaViT.utils.losses.AViTPonderLoss
        weight: 0.0005
noise:
  desc: null
  value: {}
workspace:
  desc: null
  value: AdaViT
experiments_dir:
  desc: null
  value: AdaViT/runs/
experiment_name:
  desc: null
  value: 2024-04-26-11-31-30
device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 31
load_from:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1714131091.0
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.16.5
      8:
      - 2
      - 5
      13: linux-x86_64
